---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 500M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: ubuntu/mysql:edge
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_PASSWORD
          value: "myS&cret"
        - name: MYSQL_USER
          value: "john"
        volumeMounts:
        - name: mysql-config-volume
          mountPath: /etc/mysql/mysql.conf.d/my-custom.cnf
          subPath: my-custom.cnf
        - name: mysql-data
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
      volumes:
        - name: mysql-config-volume
          configMap:
            name: mysql-config
            items:
            - key: main-config
              path: my-custom.cnf
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30306
    name: mysql
